# This file was generated by GoReleaser. DO NOT EDIT.
class Cbox < Formula
  desc "Store and organize useful shell commands or code snippets and share them with your team"
  homepage "https://cbox.dplabs.io"
  url "https://github.com/dplabs/cbox/releases/download/v1.0.0-alpha.1/cbox_1.0.0-alpha.1_macosx_x86_64.tar.gz"
  version "1.0.0-alpha.1"
  sha256 "7e09db7cdfbb13d0cfe71de38f11d082a94342cad4c06b044408404c0cf504a7"
  
  depends_on "fzf"

  def install
    bin.install "cbox"
  end

  test do
    system "#{bin}/cbox", "version"
  end
end
